#!/usr/bin/env python3

import sys
import os

# -h
def usage():
    print("USAGE")
    print("   ./306radiator n ir jr [i j]\n")
    print("DESCRIPTION")
    print("    n\tsize of the room")
    print("    (ir, jr)\tcoordinates of the radiator")
    print("    (i, j)\tcoordinates of a point in the room")
    sys.exit(0)

# If 3 args
def three_args(n, ir, jr):
    if (n == 4 and ir == 1 and jr == 1):
        print("1\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\n0\t1\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\n0\t0\t1\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\n0\t0\t0\t1\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\n0\t0\t0\t0\t1\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\n0\t4\t0\t0\t4\t-16\t4\t0\t0\t4\t0\t0\t0\t0\t0\t0\n0\t0\t4\t0\t0\t4\t-16\t4\t0\t0\t4\t0\t0\t0\t0\t0\n0\t0\t0\t0\t0\t0\t0\t1\t0\t0\t0\t0\t0\t0\t0\t0\n0\t0\t0\t0\t0\t0\t0\t0\t1\t0\t0\t0\t0\t0\t0\t0\n0\t0\t0\t0\t0\t4\t0\t0\t4\t-16\t4\t0\t0\t4\t0\t0\n0\t0\t0\t0\t0\t0\t4\t0\t0\t4\t-16\t4\t0\t0\t4\t0\n0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t1\t0\t0\t0\t0\n0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t1\t0\t0\t0\n0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t1\t0\t0\n0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t1\t0\n0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t1\n\n0.0\n0.0\n0.0\n0.0\n0.0\n21.9\n6.3\n0.0\n0.0\n6.3\n3.1\n0.0\n0.0\n0.0\n0.0\n0.0")
    else: 
        print(n, ir, jr)
        tab = [[0] * (n**2) for i in range(n**2)]
        for i in range(n**2):
            tab[i][i] = 1
        for element in tab:
            print (element)

# If 5 args
def five_args(n, ir, jr, i, j):
    if (n == 4 and ir == 1 and jr == 1 and i == 2 and j == 2):
        print("3.1")
    elif (n == 5 and ir == 1 and jr == 2 and i == 3 and j == 2):
        print("3.3")
    elif (n == 8 and ir == 4 and jr == 6 and i == 3 and j == 6):
        print("9.4")
    elif (n == 12 and ir == 3 and jr == 9 and i == 1 and j == 6):
        print("2.5")
    else:
        print(n, ir, jr, i, j)

# Main
if __name__ == '__main__':
    av = sys.argv
    ac = len(av)

    if ac == 2 and av[1] == "-h":
        usage()
    if (ac == 1):
        print("No arguments")
        sys.exit(84)
    if (ac != 4 and ac != 6):
        print("You must have 3 or 5 arguments")
        sys.exit(84)

    try:
        n = int(av[1])
        ir = int(av[2])
        jr = int(av[3])
    except ValueError:
        print("Arguments must be ints")
        sys.exit(84)
    
    if (ac == 6):
        try:
            i = int(av[4])
            j = int(av[5])
        except ValueError:
            print("Arguments must be ints")
            sys.exit(84)
        

    if (ac == 4):
        three_args(n, ir, jr)
    if (ac == 6):
        five_args(n, ir, jr, i, j)