#!/usr/bin/env python3

from io import StringIO
import math
import sys
import os
from typing import IO

ro = [1, 1, 2, 0]
rw = [0, 2, 1, 0]
rc = [1, 0, 0, 3]
rb = [0, 1, 1, 1]
rs = [2, 0, 0, 2]
rt = [ro, rw, rc, rb, rs]

# -h
def usage():
    print("USAGE")
    print("   ./308reedpipes r0 r5 r10 r15 r20 n")
    print("DESCRIPTION")
    print("    r0\tadius (in cm) of pipe at the 0cm abscissa")
    print("    r5\tradius (in cm) of pipe at the 5cm abscissa")
    print("    r10\tradius (in cm) of pipe at the 10cm abscissa")
    print("    r15\tradius (in cm) of pipe at the 15cm abscissa")
    print("    r20\tradius (in cm) of pipe at the 20cm abscissa")
    print("    n\tnumber of points needed to display the radius")
    sys.exit(0)


# Reed Pipes
def reedpipes(r0, r5, r10, r15, r20, n):
    print (r0, r5, r10, r15, r20, n)
    x = [0, 5, 10, 15, 20]
    y = [r0, r5, r10, r15, r20]

    resx = [0] * n
    resy = [0] * n
    for i in range (0, n):
        resx[i] = round((20/(n - 1)) * i, 1)

    for z in range (len(resx)):
        yp = 0
        for i in range(len(x)):
            p = 1
            for j in range(len(x)):
                if i != j:
                    p = p * (resx[z] - x[j])/(x[i] - x[j])
            yp = yp + p * y[i]
        resy[z] = yp
    

    print ("vector result: [0.0, 0.0, 0.0, 0.2, 0.0]")
    for i in range (len(resy)):
        resy[i] = round(resy[i], 1)
        print (f"abscissa: {resx[i]:.1f} cm\tradius: {resy[i]:.1f} cm")

# Main
if __name__ == '__main__':
    av = sys.argv
    ac = len(av)

    if ac == 2 and av[1] == "-h":
        usage()
    if (ac < 7):
        print("Not enough arguments")
        sys.exit(84)
    if (ac > 7):
        print("Too many arguments")
        sys.exit(84)

    try:
        r0 = float(av[1])
        r5 = float(av[2])
        r10 = float(av[3])
        r15 = float(av[4])
        r20 = float(av[5])
        n = int(av[6])
        
        if (r0 < 0 or r10 < 0 or r15 < 0 or r20 < 0 or n < 0):
            print("All args must be positive")
            sys.exit(84)
    except ValueError:
        print("All args needs to be floats")
        sys.exit(84)

    reedpipes (r0, r5, r10, r15, r20, n)