#!/usr/bin/env python3

import math
import sys

# -h
def usage():
    print("USAGE")
    print("   ./209poll pSize sSize p")
    print("DESCRIPTION")
    print("    pSize\tsize of the population")
    print("    sSize\tsize of the sample (supposed to be representative)")
    print("    p\tpercentage of voting intentions for a specific candidate")
    sys.exit(0)

# Main function
def poll(a, b, c):
    c /= 100
    var = ((c * (1 - c)) / b) * ((a - b) / (a - 1));
    t95 = [(c - 1.96 * math.sqrt(var)) * 100, (c + 1.96 * math.sqrt(var)) * 100]
    t99 = [(c - 2.58 * math.sqrt(var)) * 100, (c + 2.58 * math.sqrt(var)) * 100]

# Prints
    print (f"Population size:\t\t{a}")
    print (f"Sample size:\t\t\t{b}")
    print (f"Voting intentions:\t\t{c * 100:.2f}%")
    print (f"Variance:\t\t\t{var:.6f}")
    print (f"95% confidence interval:\t[{t95[0]:.2f}%; {t95[1]:.2f}%]")
    print (f"99% confidence interval:\t[{t99[0]:.2f}%; {t99[1]:.2f}%]")
    

# Main
if __name__ == '__main__':
    av = sys.argv
    ac = len(av)

    if ac == 2 and av[1] == "-h":
        usage()
    if (ac < 4):
        print("Not enough arguments")
        sys.exit(84)
    if (ac > 4):
        print("Too many arguments")
        sys.exit(84)

    try:
        a = int(av[1])
        b = int(av[2])
        c = float(av[3])
    except ValueError:
        print ("Arguments must be integers")
        sys.exit(84)

    if (c < 0 or c > 100):
        print ("A percentage must be between 0 and 100")
        sys.exit(84)
    if (a < 0 or b < 0):
        print ("pSize and sSize must be positive numbers")
        sys.exit(84)
    if (b > a):
        print ("sSize must be inferior to pSize")
        sys.exit(84)


    poll(a, b, c)