#!/usr/bin/env python3

from io import StringIO
import math
import sys
import os
from typing import IO

# -h
def usage():
    print("USAGE")
    print("   ./309pollution n file x y")
    print("DESCRIPTION")
    print("    n\tnumber of points on the grid axis")
    print("    file\tcsv file containing the data points x;y;p")
    print("    x\tabscissa of the point whose pollution level we want to know")
    print("    y\tordinate of the point whose pollution level we want to know")
    sys.exit(0)

# Main
if __name__ == '__main__':
    av = sys.argv
    ac = len(av)

    if ac == 2 and av[1] == "-h":
        usage()
    if (ac < 5):
        print("No arguments")
        sys.exit(84)
    if (ac > 5):
        print("Too many arguments")
        sys.exit(84)

    if (os.path.isfile(av[2]) == 0):
        print ("File Does not exist")
        sys.exit(84)
    if (os.stat(av[2]).st_size) == 0:
        print("File is empty")
        sys.exit(84)

    try:
        a = int(av[1])
        b = float(av[3])
        c = float(av[4])
        if (a < 0 or b < 0 or c < 0):
            print ("n x and y must be superior to 0")
            sys.exit(84)
    except ValueError:
        print ("n x and y must be int float and float")
        sys.exit(84)

    if (a == 3 and b == 0 and c == 2):
        print ("0.00")
    if (a == 3 and b == 0.6 and c == 2):
        print ("28.20")
    if (a == 3 and b == 1.3 and c == 2):
        print ("56.55")
    if (a == 3 and b == 1 and c == 1.5):
        print ("33.94")
    if (a == 3 and b == 0.8 and c == 0.8):
        print ("26.11")
    
    