#!/usr/bin/env python3

import math
import sys

# -h
def usage():
    print("USAGE")
    print("   ./205IQ u s [IQ1] [IQ2]\n")
    print("DESCRIPTION")
    print("    a       constant")
    sys.exit(0)

# If 2 args
def qi_a(a, b):
    for x in range (0, 201):
        step1 = 1 / (b * math.sqrt(2 * math.pi))
        step2 = math.exp(- (math.pow(x - a, 2) / (2 * math.pow(b, 2))))
        res = step1 * step2
        print (f"{x} {res:.5f}")
    sys.exit(0)

# If 3 args
def qi_b(a, b, c):
    sum = 0
    x = 0

    while x < c:
        step1 = 1 / (b * math.sqrt(2 * math.pi))
        step2 = math.exp(- (math.pow(x - a, 2) / (2 * math.pow(b, 2))))
        res = step1 * step2
        sum += res / 1000
        x += 0.001

    print(f"{sum * 100:.1f}% of people have an IQ inferior to {c}")
    sys.exit(0)

# If 4 args
def qi_c(a, b, c, d):
    sum = 0
    x = c

    while x < d:
        step1 = 1 / (b * math.sqrt(2 * math.pi))
        step2 = math.exp(- (math.pow(x - a, 2) / (2 * math.pow(b, 2))))
        res = step1 * step2
        sum += res / 1000
        x += 0.001

    print(f"{sum * 100:.1f}% of people have an IQ between {c} and {d}")
    sys.exit(0)

# Main
if __name__ == '__main__':
    av = sys.argv
    ac = len(av)

    if ac == 2 and av[1] == "-h":
        usage()
    if (ac < 3):
        print("Not enough arguments")
        sys.exit(84)
    if ac > 5:
        print("Too Many Arguments")
        sys.exit(84)

    try:
        a = int(av[1])
        b = int(av[2])
    except ValueError:
        print("All numbers needs to be NUMBERS pls :)")
        sys.exit(84)
    if a < 0 or a > 200:
        print("Mean must be between 0 and 200")
        sys.exit(84)
    if b <= 0 or b > 200:
        print("Deviation must be between 0 and 200")
        sys.exit(84)
    if ac == 3:
        qi_a(a, b)

    try:
        c = int(av[3])
    except ValueError:
        print("All numbers needs to be NUMBERS pls :)")
        sys.exit(84)
    if c < 0 or c > 200:
        print("QI can't be superior to 200 or inferior to 0")
        sys.exit(84)
    if ac == 4:
        qi_b(a, b, c)

    try:
        d = int(av[4])
    except ValueError:
        print("All numbers needs to be NUMBERS pls :)")
        sys.exit(84)
    if d < 0 or d > 200:
        print("QI can't be superior to 200 or inferior to 0")
        sys.exit(84)
    if c > d:
        print("QI1 can't be superior to QI2")
        sys.exit(84)
    qi_c(a, b, c, d)